name: Run tests

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18, 1.19 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOPATH: ${{ env.HOME }}

      - name: Print environment
        run: go env

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -cover ./...

  test_arm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        env:
          GOPATH: ${{ env.HOME }}

      - name: Run tests
        uses: uraimo/run-on-arch-action@v2
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu22.04
          run: go test -v -cover .
